// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: baseprotocol.proto

#include "baseprotocol.pb.h"
#include "baseprotocol.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace baseprotocol {

static const char* BasicStringServer_method_names[] = {
  "/baseprotocol.BasicStringServer/HandleUploadString",
};

std::unique_ptr< BasicStringServer::Stub> BasicStringServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BasicStringServer::Stub> stub(new BasicStringServer::Stub(channel, options));
  return stub;
}

BasicStringServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_HandleUploadString_(BasicStringServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BasicStringServer::Stub::HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::baseprotocol::RecievedCipherText* response) {
  return ::grpc::internal::BlockingUnaryCall< ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleUploadString_, context, request, response);
}

void BasicStringServer::Stub::async::HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleUploadString_, context, request, response, std::move(f));
}

void BasicStringServer::Stub::async::HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleUploadString_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>* BasicStringServer::Stub::PrepareAsyncHandleUploadStringRaw(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::baseprotocol::RecievedCipherText, ::baseprotocol::Ciphertext, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleUploadString_, context, request);
}

::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>* BasicStringServer::Stub::AsyncHandleUploadStringRaw(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleUploadStringRaw(context, request, cq);
  result->StartCall();
  return result;
}

BasicStringServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BasicStringServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BasicStringServer::Service, ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BasicStringServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::baseprotocol::Ciphertext* req,
             ::baseprotocol::RecievedCipherText* resp) {
               return service->HandleUploadString(ctx, req, resp);
             }, this)));
}

BasicStringServer::Service::~Service() {
}

::grpc::Status BasicStringServer::Service::HandleUploadString(::grpc::ServerContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace baseprotocol

