// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: baseprotocol.proto
// Original file comments:
// taking the hello world example so that I can create a CMAKE file
// and correctly link everything that I need
//
#ifndef GRPC_baseprotocol_2eproto__INCLUDED
#define GRPC_baseprotocol_2eproto__INCLUDED

#include "baseprotocol.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace baseprotocol {

// service EncryptedContentUpload {
//  // stream the file up in chunks
//  rpc UploadFile(stream FileUpload) returns (FileRecieved) {}
// }
//
class BasicStringServer final {
 public:
  static constexpr char const* service_full_name() {
    return "baseprotocol.BasicStringServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::baseprotocol::RecievedCipherText* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::baseprotocol::RecievedCipherText>> AsyncHandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::baseprotocol::RecievedCipherText>>(AsyncHandleUploadStringRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::baseprotocol::RecievedCipherText>> PrepareAsyncHandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::baseprotocol::RecievedCipherText>>(PrepareAsyncHandleUploadStringRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::baseprotocol::RecievedCipherText>* AsyncHandleUploadStringRaw(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::baseprotocol::RecievedCipherText>* PrepareAsyncHandleUploadStringRaw(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::baseprotocol::RecievedCipherText* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>> AsyncHandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>>(AsyncHandleUploadStringRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>> PrepareAsyncHandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>>(PrepareAsyncHandleUploadStringRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response, std::function<void(::grpc::Status)>) override;
      void HandleUploadString(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>* AsyncHandleUploadStringRaw(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::baseprotocol::RecievedCipherText>* PrepareAsyncHandleUploadStringRaw(::grpc::ClientContext* context, const ::baseprotocol::Ciphertext& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_HandleUploadString_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status HandleUploadString(::grpc::ServerContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_HandleUploadString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_HandleUploadString() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_HandleUploadString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleUploadString(::grpc::ServerContext* /*context*/, const ::baseprotocol::Ciphertext* /*request*/, ::baseprotocol::RecievedCipherText* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleUploadString(::grpc::ServerContext* context, ::baseprotocol::Ciphertext* request, ::grpc::ServerAsyncResponseWriter< ::baseprotocol::RecievedCipherText>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_HandleUploadString<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_HandleUploadString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_HandleUploadString() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::baseprotocol::Ciphertext* request, ::baseprotocol::RecievedCipherText* response) { return this->HandleUploadString(context, request, response); }));}
    void SetMessageAllocatorFor_HandleUploadString(
        ::grpc::MessageAllocator< ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_HandleUploadString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleUploadString(::grpc::ServerContext* /*context*/, const ::baseprotocol::Ciphertext* /*request*/, ::baseprotocol::RecievedCipherText* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HandleUploadString(
      ::grpc::CallbackServerContext* /*context*/, const ::baseprotocol::Ciphertext* /*request*/, ::baseprotocol::RecievedCipherText* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_HandleUploadString<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_HandleUploadString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_HandleUploadString() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_HandleUploadString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleUploadString(::grpc::ServerContext* /*context*/, const ::baseprotocol::Ciphertext* /*request*/, ::baseprotocol::RecievedCipherText* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_HandleUploadString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_HandleUploadString() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_HandleUploadString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleUploadString(::grpc::ServerContext* /*context*/, const ::baseprotocol::Ciphertext* /*request*/, ::baseprotocol::RecievedCipherText* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleUploadString(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_HandleUploadString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_HandleUploadString() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->HandleUploadString(context, request, response); }));
    }
    ~WithRawCallbackMethod_HandleUploadString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleUploadString(::grpc::ServerContext* /*context*/, const ::baseprotocol::Ciphertext* /*request*/, ::baseprotocol::RecievedCipherText* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HandleUploadString(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HandleUploadString : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_HandleUploadString() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::baseprotocol::Ciphertext, ::baseprotocol::RecievedCipherText>* streamer) {
                       return this->StreamedHandleUploadString(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_HandleUploadString() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HandleUploadString(::grpc::ServerContext* /*context*/, const ::baseprotocol::Ciphertext* /*request*/, ::baseprotocol::RecievedCipherText* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandleUploadString(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::baseprotocol::Ciphertext,::baseprotocol::RecievedCipherText>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_HandleUploadString<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_HandleUploadString<Service > StreamedService;
};

}  // namespace baseprotocol


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_baseprotocol_2eproto__INCLUDED
