// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: baseprotocol.proto
// Protobuf C++ Version: 5.29.0

#ifndef baseprotocol_2eproto_2epb_2eh
#define baseprotocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_baseprotocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_baseprotocol_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_baseprotocol_2eproto;
namespace baseprotocol {
class Ciphertext;
struct CiphertextDefaultTypeInternal;
extern CiphertextDefaultTypeInternal _Ciphertext_default_instance_;
class FileChunk;
struct FileChunkDefaultTypeInternal;
extern FileChunkDefaultTypeInternal _FileChunk_default_instance_;
class FileHeaderData;
struct FileHeaderDataDefaultTypeInternal;
extern FileHeaderDataDefaultTypeInternal _FileHeaderData_default_instance_;
class FileUpload;
struct FileUploadDefaultTypeInternal;
extern FileUploadDefaultTypeInternal _FileUpload_default_instance_;
class RecievedCipherText;
struct RecievedCipherTextDefaultTypeInternal;
extern RecievedCipherTextDefaultTypeInternal _RecievedCipherText_default_instance_;
}  // namespace baseprotocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace baseprotocol {

// ===================================================================


// -------------------------------------------------------------------

class RecievedCipherText final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:baseprotocol.RecievedCipherText) */ {
 public:
  inline RecievedCipherText() : RecievedCipherText(nullptr) {}
  ~RecievedCipherText() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RecievedCipherText* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RecievedCipherText));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RecievedCipherText(
      ::google::protobuf::internal::ConstantInitialized);

  inline RecievedCipherText(const RecievedCipherText& from) : RecievedCipherText(nullptr, from) {}
  inline RecievedCipherText(RecievedCipherText&& from) noexcept
      : RecievedCipherText(nullptr, std::move(from)) {}
  inline RecievedCipherText& operator=(const RecievedCipherText& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecievedCipherText& operator=(RecievedCipherText&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecievedCipherText& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecievedCipherText* internal_default_instance() {
    return reinterpret_cast<const RecievedCipherText*>(
        &_RecievedCipherText_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RecievedCipherText& a, RecievedCipherText& b) { a.Swap(&b); }
  inline void Swap(RecievedCipherText* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecievedCipherText* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecievedCipherText* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RecievedCipherText>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RecievedCipherText& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RecievedCipherText& from) { RecievedCipherText::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RecievedCipherText* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "baseprotocol.RecievedCipherText"; }

 protected:
  explicit RecievedCipherText(::google::protobuf::Arena* arena);
  RecievedCipherText(::google::protobuf::Arena* arena, const RecievedCipherText& from);
  RecievedCipherText(::google::protobuf::Arena* arena, RecievedCipherText&& from) noexcept
      : RecievedCipherText(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgFieldNumber = 1,
  };
  // string msg = 1;
  void clear_msg() ;
  const std::string& msg() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* value);

  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(
      const std::string& value);
  std::string* _internal_mutable_msg();

  public:
  // @@protoc_insertion_point(class_scope:baseprotocol.RecievedCipherText)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      43, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RecievedCipherText& from_msg);
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_baseprotocol_2eproto;
};
// -------------------------------------------------------------------

class FileHeaderData final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:baseprotocol.FileHeaderData) */ {
 public:
  inline FileHeaderData() : FileHeaderData(nullptr) {}
  ~FileHeaderData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileHeaderData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileHeaderData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileHeaderData(
      ::google::protobuf::internal::ConstantInitialized);

  inline FileHeaderData(const FileHeaderData& from) : FileHeaderData(nullptr, from) {}
  inline FileHeaderData(FileHeaderData&& from) noexcept
      : FileHeaderData(nullptr, std::move(from)) {}
  inline FileHeaderData& operator=(const FileHeaderData& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileHeaderData& operator=(FileHeaderData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileHeaderData& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileHeaderData* internal_default_instance() {
    return reinterpret_cast<const FileHeaderData*>(
        &_FileHeaderData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(FileHeaderData& a, FileHeaderData& b) { a.Swap(&b); }
  inline void Swap(FileHeaderData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileHeaderData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileHeaderData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileHeaderData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileHeaderData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileHeaderData& from) { FileHeaderData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileHeaderData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "baseprotocol.FileHeaderData"; }

 protected:
  explicit FileHeaderData(::google::protobuf::Arena* arena);
  FileHeaderData(::google::protobuf::Arena* arena, const FileHeaderData& from);
  FileHeaderData(::google::protobuf::Arena* arena, FileHeaderData&& from) noexcept
      : FileHeaderData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientNameFieldNumber = 1,
    kFilenameFieldNumber = 2,
    kIvFieldNumber = 3,
    kCFieldNumber = 4,
    kNumbitsinZZFieldNumber = 5,
  };
  // string clientName = 1;
  void clear_clientname() ;
  const std::string& clientname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_clientname(Arg_&& arg, Args_... args);
  std::string* mutable_clientname();
  PROTOBUF_NODISCARD std::string* release_clientname();
  void set_allocated_clientname(std::string* value);

  private:
  const std::string& _internal_clientname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientname(
      const std::string& value);
  std::string* _internal_mutable_clientname();

  public:
  // string filename = 2;
  void clear_filename() ;
  const std::string& filename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* value);

  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(
      const std::string& value);
  std::string* _internal_mutable_filename();

  public:
  // bytes iv = 3;
  void clear_iv() ;
  const std::string& iv() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_iv(Arg_&& arg, Args_... args);
  std::string* mutable_iv();
  PROTOBUF_NODISCARD std::string* release_iv();
  void set_allocated_iv(std::string* value);

  private:
  const std::string& _internal_iv() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_iv(
      const std::string& value);
  std::string* _internal_mutable_iv();

  public:
  // bytes c = 4;
  void clear_c() ;
  const std::string& c() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_c(Arg_&& arg, Args_... args);
  std::string* mutable_c();
  PROTOBUF_NODISCARD std::string* release_c();
  void set_allocated_c(std::string* value);

  private:
  const std::string& _internal_c() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_c(
      const std::string& value);
  std::string* _internal_mutable_c();

  public:
  // int64 numbitsinZZ = 5;
  void clear_numbitsinzz() ;
  ::int64_t numbitsinzz() const;
  void set_numbitsinzz(::int64_t value);

  private:
  ::int64_t _internal_numbitsinzz() const;
  void _internal_set_numbitsinzz(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:baseprotocol.FileHeaderData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      54, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const FileHeaderData& from_msg);
    ::google::protobuf::internal::ArenaStringPtr clientname_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::google::protobuf::internal::ArenaStringPtr iv_;
    ::google::protobuf::internal::ArenaStringPtr c_;
    ::int64_t numbitsinzz_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_baseprotocol_2eproto;
};
// -------------------------------------------------------------------

class FileChunk final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:baseprotocol.FileChunk) */ {
 public:
  inline FileChunk() : FileChunk(nullptr) {}
  ~FileChunk() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileChunk* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileChunk));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileChunk(
      ::google::protobuf::internal::ConstantInitialized);

  inline FileChunk(const FileChunk& from) : FileChunk(nullptr, from) {}
  inline FileChunk(FileChunk&& from) noexcept
      : FileChunk(nullptr, std::move(from)) {}
  inline FileChunk& operator=(const FileChunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileChunk& operator=(FileChunk&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileChunk& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileChunk* internal_default_instance() {
    return reinterpret_cast<const FileChunk*>(
        &_FileChunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(FileChunk& a, FileChunk& b) { a.Swap(&b); }
  inline void Swap(FileChunk* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileChunk* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileChunk* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileChunk>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileChunk& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileChunk& from) { FileChunk::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileChunk* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "baseprotocol.FileChunk"; }

 protected:
  explicit FileChunk(::google::protobuf::Arena* arena);
  FileChunk(::google::protobuf::Arena* arena, const FileChunk& from);
  FileChunk(::google::protobuf::Arena* arena, FileChunk&& from) noexcept
      : FileChunk(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFileDataChunkFieldNumber = 1,
  };
  // bytes fileDataChunk = 1;
  void clear_filedatachunk() ;
  const std::string& filedatachunk() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filedatachunk(Arg_&& arg, Args_... args);
  std::string* mutable_filedatachunk();
  PROTOBUF_NODISCARD std::string* release_filedatachunk();
  void set_allocated_filedatachunk(std::string* value);

  private:
  const std::string& _internal_filedatachunk() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filedatachunk(
      const std::string& value);
  std::string* _internal_mutable_filedatachunk();

  public:
  // @@protoc_insertion_point(class_scope:baseprotocol.FileChunk)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const FileChunk& from_msg);
    ::google::protobuf::internal::ArenaStringPtr filedatachunk_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_baseprotocol_2eproto;
};
// -------------------------------------------------------------------

class Ciphertext final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:baseprotocol.Ciphertext) */ {
 public:
  inline Ciphertext() : Ciphertext(nullptr) {}
  ~Ciphertext() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Ciphertext* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Ciphertext));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Ciphertext(
      ::google::protobuf::internal::ConstantInitialized);

  inline Ciphertext(const Ciphertext& from) : Ciphertext(nullptr, from) {}
  inline Ciphertext(Ciphertext&& from) noexcept
      : Ciphertext(nullptr, std::move(from)) {}
  inline Ciphertext& operator=(const Ciphertext& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ciphertext& operator=(Ciphertext&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ciphertext& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ciphertext* internal_default_instance() {
    return reinterpret_cast<const Ciphertext*>(
        &_Ciphertext_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Ciphertext& a, Ciphertext& b) { a.Swap(&b); }
  inline void Swap(Ciphertext* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ciphertext* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ciphertext* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Ciphertext>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Ciphertext& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Ciphertext& from) { Ciphertext::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Ciphertext* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "baseprotocol.Ciphertext"; }

 protected:
  explicit Ciphertext(::google::protobuf::Arena* arena);
  Ciphertext(::google::protobuf::Arena* arena, const Ciphertext& from);
  Ciphertext(::google::protobuf::Arena* arena, Ciphertext&& from) noexcept
      : Ciphertext(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCprimeFieldNumber = 1,
    kIvFieldNumber = 2,
    kCFieldNumber = 3,
    kCprimeLengthFieldNumber = 4,
  };
  // bytes cprime = 1;
  void clear_cprime() ;
  const std::string& cprime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cprime(Arg_&& arg, Args_... args);
  std::string* mutable_cprime();
  PROTOBUF_NODISCARD std::string* release_cprime();
  void set_allocated_cprime(std::string* value);

  private:
  const std::string& _internal_cprime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cprime(
      const std::string& value);
  std::string* _internal_mutable_cprime();

  public:
  // string iv = 2;
  void clear_iv() ;
  const std::string& iv() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_iv(Arg_&& arg, Args_... args);
  std::string* mutable_iv();
  PROTOBUF_NODISCARD std::string* release_iv();
  void set_allocated_iv(std::string* value);

  private:
  const std::string& _internal_iv() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_iv(
      const std::string& value);
  std::string* _internal_mutable_iv();

  public:
  // string c = 3;
  void clear_c() ;
  const std::string& c() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_c(Arg_&& arg, Args_... args);
  std::string* mutable_c();
  PROTOBUF_NODISCARD std::string* release_c();
  void set_allocated_c(std::string* value);

  private:
  const std::string& _internal_c() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_c(
      const std::string& value);
  std::string* _internal_mutable_c();

  public:
  // int64 cprimeLength = 4;
  void clear_cprimelength() ;
  ::int64_t cprimelength() const;
  void set_cprimelength(::int64_t value);

  private:
  ::int64_t _internal_cprimelength() const;
  void _internal_set_cprimelength(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:baseprotocol.Ciphertext)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      35, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Ciphertext& from_msg);
    ::google::protobuf::internal::ArenaStringPtr cprime_;
    ::google::protobuf::internal::ArenaStringPtr iv_;
    ::google::protobuf::internal::ArenaStringPtr c_;
    ::int64_t cprimelength_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_baseprotocol_2eproto;
};
// -------------------------------------------------------------------

class FileUpload final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:baseprotocol.FileUpload) */ {
 public:
  inline FileUpload() : FileUpload(nullptr) {}
  ~FileUpload() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileUpload* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileUpload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileUpload(
      ::google::protobuf::internal::ConstantInitialized);

  inline FileUpload(const FileUpload& from) : FileUpload(nullptr, from) {}
  inline FileUpload(FileUpload&& from) noexcept
      : FileUpload(nullptr, std::move(from)) {}
  inline FileUpload& operator=(const FileUpload& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileUpload& operator=(FileUpload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileUpload& default_instance() {
    return *internal_default_instance();
  }
  enum FileCase {
    kFhd = 1,
    kFc = 2,
    kFoobar = 3,
    FILE_NOT_SET = 0,
  };
  static inline const FileUpload* internal_default_instance() {
    return reinterpret_cast<const FileUpload*>(
        &_FileUpload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FileUpload& a, FileUpload& b) { a.Swap(&b); }
  inline void Swap(FileUpload* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileUpload* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileUpload* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileUpload>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileUpload& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileUpload& from) { FileUpload::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileUpload* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "baseprotocol.FileUpload"; }

 protected:
  explicit FileUpload(::google::protobuf::Arena* arena);
  FileUpload(::google::protobuf::Arena* arena, const FileUpload& from);
  FileUpload(::google::protobuf::Arena* arena, FileUpload&& from) noexcept
      : FileUpload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFhdFieldNumber = 1,
    kFcFieldNumber = 2,
    kFoobarFieldNumber = 3,
  };
  // .baseprotocol.FileHeaderData fhd = 1;
  bool has_fhd() const;
  private:
  bool _internal_has_fhd() const;

  public:
  void clear_fhd() ;
  const ::baseprotocol::FileHeaderData& fhd() const;
  PROTOBUF_NODISCARD ::baseprotocol::FileHeaderData* release_fhd();
  ::baseprotocol::FileHeaderData* mutable_fhd();
  void set_allocated_fhd(::baseprotocol::FileHeaderData* value);
  void unsafe_arena_set_allocated_fhd(::baseprotocol::FileHeaderData* value);
  ::baseprotocol::FileHeaderData* unsafe_arena_release_fhd();

  private:
  const ::baseprotocol::FileHeaderData& _internal_fhd() const;
  ::baseprotocol::FileHeaderData* _internal_mutable_fhd();

  public:
  // .baseprotocol.FileChunk fc = 2;
  bool has_fc() const;
  private:
  bool _internal_has_fc() const;

  public:
  void clear_fc() ;
  const ::baseprotocol::FileChunk& fc() const;
  PROTOBUF_NODISCARD ::baseprotocol::FileChunk* release_fc();
  ::baseprotocol::FileChunk* mutable_fc();
  void set_allocated_fc(::baseprotocol::FileChunk* value);
  void unsafe_arena_set_allocated_fc(::baseprotocol::FileChunk* value);
  ::baseprotocol::FileChunk* unsafe_arena_release_fc();

  private:
  const ::baseprotocol::FileChunk& _internal_fc() const;
  ::baseprotocol::FileChunk* _internal_mutable_fc();

  public:
  // string foobar = 3;
  bool has_foobar() const;
  void clear_foobar() ;
  const std::string& foobar() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_foobar(Arg_&& arg, Args_... args);
  std::string* mutable_foobar();
  PROTOBUF_NODISCARD std::string* release_foobar();
  void set_allocated_foobar(std::string* value);

  private:
  const std::string& _internal_foobar() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_foobar(
      const std::string& value);
  std::string* _internal_mutable_foobar();

  public:
  void clear_file();
  FileCase file_case() const;
  // @@protoc_insertion_point(class_scope:baseprotocol.FileUpload)
 private:
  class _Internal;
  void set_has_fhd();
  void set_has_fc();
  void set_has_foobar();
  inline bool has_file() const;
  inline void clear_has_file();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 2,
      38, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const FileUpload& from_msg);
    union FileUnion {
      constexpr FileUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::baseprotocol::FileHeaderData* fhd_;
      ::baseprotocol::FileChunk* fc_;
      ::google::protobuf::internal::ArenaStringPtr foobar_;
    } file_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_baseprotocol_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Ciphertext

// bytes cprime = 1;
inline void Ciphertext::clear_cprime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cprime_.ClearToEmpty();
}
inline const std::string& Ciphertext::cprime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.Ciphertext.cprime)
  return _internal_cprime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Ciphertext::set_cprime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cprime_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.Ciphertext.cprime)
}
inline std::string* Ciphertext::mutable_cprime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cprime();
  // @@protoc_insertion_point(field_mutable:baseprotocol.Ciphertext.cprime)
  return _s;
}
inline const std::string& Ciphertext::_internal_cprime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cprime_.Get();
}
inline void Ciphertext::_internal_set_cprime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cprime_.Set(value, GetArena());
}
inline std::string* Ciphertext::_internal_mutable_cprime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cprime_.Mutable( GetArena());
}
inline std::string* Ciphertext::release_cprime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.Ciphertext.cprime)
  return _impl_.cprime_.Release();
}
inline void Ciphertext::set_allocated_cprime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cprime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cprime_.IsDefault()) {
    _impl_.cprime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.Ciphertext.cprime)
}

// string iv = 2;
inline void Ciphertext::clear_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.ClearToEmpty();
}
inline const std::string& Ciphertext::iv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.Ciphertext.iv)
  return _internal_iv();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Ciphertext::set_iv(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.Ciphertext.iv)
}
inline std::string* Ciphertext::mutable_iv() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_iv();
  // @@protoc_insertion_point(field_mutable:baseprotocol.Ciphertext.iv)
  return _s;
}
inline const std::string& Ciphertext::_internal_iv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iv_.Get();
}
inline void Ciphertext::_internal_set_iv(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.Set(value, GetArena());
}
inline std::string* Ciphertext::_internal_mutable_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.iv_.Mutable( GetArena());
}
inline std::string* Ciphertext::release_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.Ciphertext.iv)
  return _impl_.iv_.Release();
}
inline void Ciphertext::set_allocated_iv(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.iv_.IsDefault()) {
    _impl_.iv_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.Ciphertext.iv)
}

// string c = 3;
inline void Ciphertext::clear_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.ClearToEmpty();
}
inline const std::string& Ciphertext::c() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.Ciphertext.c)
  return _internal_c();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Ciphertext::set_c(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.Ciphertext.c)
}
inline std::string* Ciphertext::mutable_c() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_c();
  // @@protoc_insertion_point(field_mutable:baseprotocol.Ciphertext.c)
  return _s;
}
inline const std::string& Ciphertext::_internal_c() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.c_.Get();
}
inline void Ciphertext::_internal_set_c(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.Set(value, GetArena());
}
inline std::string* Ciphertext::_internal_mutable_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.c_.Mutable( GetArena());
}
inline std::string* Ciphertext::release_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.Ciphertext.c)
  return _impl_.c_.Release();
}
inline void Ciphertext::set_allocated_c(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.c_.IsDefault()) {
    _impl_.c_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.Ciphertext.c)
}

// int64 cprimeLength = 4;
inline void Ciphertext::clear_cprimelength() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cprimelength_ = ::int64_t{0};
}
inline ::int64_t Ciphertext::cprimelength() const {
  // @@protoc_insertion_point(field_get:baseprotocol.Ciphertext.cprimeLength)
  return _internal_cprimelength();
}
inline void Ciphertext::set_cprimelength(::int64_t value) {
  _internal_set_cprimelength(value);
  // @@protoc_insertion_point(field_set:baseprotocol.Ciphertext.cprimeLength)
}
inline ::int64_t Ciphertext::_internal_cprimelength() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cprimelength_;
}
inline void Ciphertext::_internal_set_cprimelength(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cprimelength_ = value;
}

// -------------------------------------------------------------------

// RecievedCipherText

// string msg = 1;
inline void RecievedCipherText::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& RecievedCipherText::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.RecievedCipherText.msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RecievedCipherText::set_msg(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.RecievedCipherText.msg)
}
inline std::string* RecievedCipherText::mutable_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:baseprotocol.RecievedCipherText.msg)
  return _s;
}
inline const std::string& RecievedCipherText::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void RecievedCipherText::_internal_set_msg(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(value, GetArena());
}
inline std::string* RecievedCipherText::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msg_.Mutable( GetArena());
}
inline std::string* RecievedCipherText::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.RecievedCipherText.msg)
  return _impl_.msg_.Release();
}
inline void RecievedCipherText::set_allocated_msg(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.RecievedCipherText.msg)
}

// -------------------------------------------------------------------

// FileUpload

// .baseprotocol.FileHeaderData fhd = 1;
inline bool FileUpload::has_fhd() const {
  return file_case() == kFhd;
}
inline bool FileUpload::_internal_has_fhd() const {
  return file_case() == kFhd;
}
inline void FileUpload::set_has_fhd() {
  _impl_._oneof_case_[0] = kFhd;
}
inline void FileUpload::clear_fhd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (file_case() == kFhd) {
    if (GetArena() == nullptr) {
      delete _impl_.file_.fhd_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.file_.fhd_);
    }
    clear_has_file();
  }
}
inline ::baseprotocol::FileHeaderData* FileUpload::release_fhd() {
  // @@protoc_insertion_point(field_release:baseprotocol.FileUpload.fhd)
  if (file_case() == kFhd) {
    clear_has_file();
    auto* temp = _impl_.file_.fhd_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.file_.fhd_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::baseprotocol::FileHeaderData& FileUpload::_internal_fhd() const {
  return file_case() == kFhd ? *_impl_.file_.fhd_ : reinterpret_cast<::baseprotocol::FileHeaderData&>(::baseprotocol::_FileHeaderData_default_instance_);
}
inline const ::baseprotocol::FileHeaderData& FileUpload::fhd() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileUpload.fhd)
  return _internal_fhd();
}
inline ::baseprotocol::FileHeaderData* FileUpload::unsafe_arena_release_fhd() {
  // @@protoc_insertion_point(field_unsafe_arena_release:baseprotocol.FileUpload.fhd)
  if (file_case() == kFhd) {
    clear_has_file();
    auto* temp = _impl_.file_.fhd_;
    _impl_.file_.fhd_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void FileUpload::unsafe_arena_set_allocated_fhd(::baseprotocol::FileHeaderData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_file();
  if (value) {
    set_has_fhd();
    _impl_.file_.fhd_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:baseprotocol.FileUpload.fhd)
}
inline ::baseprotocol::FileHeaderData* FileUpload::_internal_mutable_fhd() {
  if (file_case() != kFhd) {
    clear_file();
    set_has_fhd();
    _impl_.file_.fhd_ =
        ::google::protobuf::Message::DefaultConstruct<::baseprotocol::FileHeaderData>(GetArena());
  }
  return _impl_.file_.fhd_;
}
inline ::baseprotocol::FileHeaderData* FileUpload::mutable_fhd() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::baseprotocol::FileHeaderData* _msg = _internal_mutable_fhd();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileUpload.fhd)
  return _msg;
}

// .baseprotocol.FileChunk fc = 2;
inline bool FileUpload::has_fc() const {
  return file_case() == kFc;
}
inline bool FileUpload::_internal_has_fc() const {
  return file_case() == kFc;
}
inline void FileUpload::set_has_fc() {
  _impl_._oneof_case_[0] = kFc;
}
inline void FileUpload::clear_fc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (file_case() == kFc) {
    if (GetArena() == nullptr) {
      delete _impl_.file_.fc_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.file_.fc_);
    }
    clear_has_file();
  }
}
inline ::baseprotocol::FileChunk* FileUpload::release_fc() {
  // @@protoc_insertion_point(field_release:baseprotocol.FileUpload.fc)
  if (file_case() == kFc) {
    clear_has_file();
    auto* temp = _impl_.file_.fc_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.file_.fc_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::baseprotocol::FileChunk& FileUpload::_internal_fc() const {
  return file_case() == kFc ? *_impl_.file_.fc_ : reinterpret_cast<::baseprotocol::FileChunk&>(::baseprotocol::_FileChunk_default_instance_);
}
inline const ::baseprotocol::FileChunk& FileUpload::fc() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileUpload.fc)
  return _internal_fc();
}
inline ::baseprotocol::FileChunk* FileUpload::unsafe_arena_release_fc() {
  // @@protoc_insertion_point(field_unsafe_arena_release:baseprotocol.FileUpload.fc)
  if (file_case() == kFc) {
    clear_has_file();
    auto* temp = _impl_.file_.fc_;
    _impl_.file_.fc_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void FileUpload::unsafe_arena_set_allocated_fc(::baseprotocol::FileChunk* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_file();
  if (value) {
    set_has_fc();
    _impl_.file_.fc_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:baseprotocol.FileUpload.fc)
}
inline ::baseprotocol::FileChunk* FileUpload::_internal_mutable_fc() {
  if (file_case() != kFc) {
    clear_file();
    set_has_fc();
    _impl_.file_.fc_ =
        ::google::protobuf::Message::DefaultConstruct<::baseprotocol::FileChunk>(GetArena());
  }
  return _impl_.file_.fc_;
}
inline ::baseprotocol::FileChunk* FileUpload::mutable_fc() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::baseprotocol::FileChunk* _msg = _internal_mutable_fc();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileUpload.fc)
  return _msg;
}

// string foobar = 3;
inline bool FileUpload::has_foobar() const {
  return file_case() == kFoobar;
}
inline void FileUpload::set_has_foobar() {
  _impl_._oneof_case_[0] = kFoobar;
}
inline void FileUpload::clear_foobar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (file_case() == kFoobar) {
    _impl_.file_.foobar_.Destroy();
    clear_has_file();
  }
}
inline const std::string& FileUpload::foobar() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileUpload.foobar)
  return _internal_foobar();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileUpload::set_foobar(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (file_case() != kFoobar) {
    clear_file();

    set_has_foobar();
    _impl_.file_.foobar_.InitDefault();
  }
  _impl_.file_.foobar_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.FileUpload.foobar)
}
inline std::string* FileUpload::mutable_foobar() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_foobar();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileUpload.foobar)
  return _s;
}
inline const std::string& FileUpload::_internal_foobar() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (file_case() != kFoobar) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.file_.foobar_.Get();
}
inline void FileUpload::_internal_set_foobar(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (file_case() != kFoobar) {
    clear_file();

    set_has_foobar();
    _impl_.file_.foobar_.InitDefault();
  }
  _impl_.file_.foobar_.Set(value, GetArena());
}
inline std::string* FileUpload::_internal_mutable_foobar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (file_case() != kFoobar) {
    clear_file();

    set_has_foobar();
    _impl_.file_.foobar_.InitDefault();
  }
  return _impl_.file_.foobar_.Mutable( GetArena());
}
inline std::string* FileUpload::release_foobar() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.FileUpload.foobar)
  if (file_case() != kFoobar) {
    return nullptr;
  }
  clear_has_file();
  return _impl_.file_.foobar_.Release();
}
inline void FileUpload::set_allocated_foobar(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_file()) {
    clear_file();
  }
  if (value != nullptr) {
    set_has_foobar();
    _impl_.file_.foobar_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileUpload.foobar)
}

inline bool FileUpload::has_file() const {
  return file_case() != FILE_NOT_SET;
}
inline void FileUpload::clear_has_file() {
  _impl_._oneof_case_[0] = FILE_NOT_SET;
}
inline FileUpload::FileCase FileUpload::file_case() const {
  return FileUpload::FileCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// FileChunk

// bytes fileDataChunk = 1;
inline void FileChunk::clear_filedatachunk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filedatachunk_.ClearToEmpty();
}
inline const std::string& FileChunk::filedatachunk() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileChunk.fileDataChunk)
  return _internal_filedatachunk();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileChunk::set_filedatachunk(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filedatachunk_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.FileChunk.fileDataChunk)
}
inline std::string* FileChunk::mutable_filedatachunk() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_filedatachunk();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileChunk.fileDataChunk)
  return _s;
}
inline const std::string& FileChunk::_internal_filedatachunk() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filedatachunk_.Get();
}
inline void FileChunk::_internal_set_filedatachunk(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filedatachunk_.Set(value, GetArena());
}
inline std::string* FileChunk::_internal_mutable_filedatachunk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.filedatachunk_.Mutable( GetArena());
}
inline std::string* FileChunk::release_filedatachunk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.FileChunk.fileDataChunk)
  return _impl_.filedatachunk_.Release();
}
inline void FileChunk::set_allocated_filedatachunk(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filedatachunk_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filedatachunk_.IsDefault()) {
    _impl_.filedatachunk_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileChunk.fileDataChunk)
}

// -------------------------------------------------------------------

// FileHeaderData

// string clientName = 1;
inline void FileHeaderData::clear_clientname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientname_.ClearToEmpty();
}
inline const std::string& FileHeaderData::clientname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileHeaderData.clientName)
  return _internal_clientname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileHeaderData::set_clientname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.FileHeaderData.clientName)
}
inline std::string* FileHeaderData::mutable_clientname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_clientname();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileHeaderData.clientName)
  return _s;
}
inline const std::string& FileHeaderData::_internal_clientname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientname_.Get();
}
inline void FileHeaderData::_internal_set_clientname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientname_.Set(value, GetArena());
}
inline std::string* FileHeaderData::_internal_mutable_clientname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.clientname_.Mutable( GetArena());
}
inline std::string* FileHeaderData::release_clientname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.FileHeaderData.clientName)
  return _impl_.clientname_.Release();
}
inline void FileHeaderData::set_allocated_clientname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.clientname_.IsDefault()) {
    _impl_.clientname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileHeaderData.clientName)
}

// string filename = 2;
inline void FileHeaderData::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& FileHeaderData::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileHeaderData.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileHeaderData::set_filename(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.FileHeaderData.filename)
}
inline std::string* FileHeaderData::mutable_filename() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileHeaderData.filename)
  return _s;
}
inline const std::string& FileHeaderData::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void FileHeaderData::_internal_set_filename(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.Set(value, GetArena());
}
inline std::string* FileHeaderData::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.filename_.Mutable( GetArena());
}
inline std::string* FileHeaderData::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.FileHeaderData.filename)
  return _impl_.filename_.Release();
}
inline void FileHeaderData::set_allocated_filename(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileHeaderData.filename)
}

// bytes iv = 3;
inline void FileHeaderData::clear_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.ClearToEmpty();
}
inline const std::string& FileHeaderData::iv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileHeaderData.iv)
  return _internal_iv();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileHeaderData::set_iv(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.FileHeaderData.iv)
}
inline std::string* FileHeaderData::mutable_iv() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_iv();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileHeaderData.iv)
  return _s;
}
inline const std::string& FileHeaderData::_internal_iv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iv_.Get();
}
inline void FileHeaderData::_internal_set_iv(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.Set(value, GetArena());
}
inline std::string* FileHeaderData::_internal_mutable_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.iv_.Mutable( GetArena());
}
inline std::string* FileHeaderData::release_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.FileHeaderData.iv)
  return _impl_.iv_.Release();
}
inline void FileHeaderData::set_allocated_iv(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.iv_.IsDefault()) {
    _impl_.iv_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileHeaderData.iv)
}

// bytes c = 4;
inline void FileHeaderData::clear_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.ClearToEmpty();
}
inline const std::string& FileHeaderData::c() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:baseprotocol.FileHeaderData.c)
  return _internal_c();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileHeaderData::set_c(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:baseprotocol.FileHeaderData.c)
}
inline std::string* FileHeaderData::mutable_c() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_c();
  // @@protoc_insertion_point(field_mutable:baseprotocol.FileHeaderData.c)
  return _s;
}
inline const std::string& FileHeaderData::_internal_c() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.c_.Get();
}
inline void FileHeaderData::_internal_set_c(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.Set(value, GetArena());
}
inline std::string* FileHeaderData::_internal_mutable_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.c_.Mutable( GetArena());
}
inline std::string* FileHeaderData::release_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:baseprotocol.FileHeaderData.c)
  return _impl_.c_.Release();
}
inline void FileHeaderData::set_allocated_c(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.c_.IsDefault()) {
    _impl_.c_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileHeaderData.c)
}

// int64 numbitsinZZ = 5;
inline void FileHeaderData::clear_numbitsinzz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbitsinzz_ = ::int64_t{0};
}
inline ::int64_t FileHeaderData::numbitsinzz() const {
  // @@protoc_insertion_point(field_get:baseprotocol.FileHeaderData.numbitsinZZ)
  return _internal_numbitsinzz();
}
inline void FileHeaderData::set_numbitsinzz(::int64_t value) {
  _internal_set_numbitsinzz(value);
  // @@protoc_insertion_point(field_set:baseprotocol.FileHeaderData.numbitsinZZ)
}
inline ::int64_t FileHeaderData::_internal_numbitsinzz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numbitsinzz_;
}
inline void FileHeaderData::_internal_set_numbitsinzz(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbitsinzz_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace baseprotocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // baseprotocol_2eproto_2epb_2eh
