// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: baseprotocol.proto
// Protobuf C++ Version: 5.29.0

#include "baseprotocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace baseprotocol {

inline constexpr RecievedCipherText::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecievedCipherText::RecievedCipherText(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RecievedCipherTextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecievedCipherTextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecievedCipherTextDefaultTypeInternal() {}
  union {
    RecievedCipherText _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecievedCipherTextDefaultTypeInternal _RecievedCipherText_default_instance_;

inline constexpr FileHeaderData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : clientname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iv_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        c_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        numbitsinzz_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileHeaderData::FileHeaderData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileHeaderDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileHeaderDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileHeaderDataDefaultTypeInternal() {}
  union {
    FileHeaderData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileHeaderDataDefaultTypeInternal _FileHeaderData_default_instance_;

inline constexpr FileChunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filedatachunk_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileChunk::FileChunk(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileChunkDefaultTypeInternal() {}
  union {
    FileChunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileChunkDefaultTypeInternal _FileChunk_default_instance_;

inline constexpr Ciphertext::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : cprime_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iv_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        c_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cprimelength_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Ciphertext::Ciphertext(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CiphertextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CiphertextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CiphertextDefaultTypeInternal() {}
  union {
    Ciphertext _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CiphertextDefaultTypeInternal _Ciphertext_default_instance_;

inline constexpr FileUpload::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : file_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR FileUpload::FileUpload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileUploadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileUploadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileUploadDefaultTypeInternal() {}
  union {
    FileUpload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileUploadDefaultTypeInternal _FileUpload_default_instance_;
}  // namespace baseprotocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_baseprotocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_baseprotocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_baseprotocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::baseprotocol::Ciphertext, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::baseprotocol::Ciphertext, _impl_.cprime_),
        PROTOBUF_FIELD_OFFSET(::baseprotocol::Ciphertext, _impl_.iv_),
        PROTOBUF_FIELD_OFFSET(::baseprotocol::Ciphertext, _impl_.c_),
        PROTOBUF_FIELD_OFFSET(::baseprotocol::Ciphertext, _impl_.cprimelength_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::baseprotocol::RecievedCipherText, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::baseprotocol::RecievedCipherText, _impl_.msg_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileUpload, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileUpload, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileUpload, _impl_.file_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileChunk, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileChunk, _impl_.filedatachunk_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileHeaderData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileHeaderData, _impl_.clientname_),
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileHeaderData, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileHeaderData, _impl_.iv_),
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileHeaderData, _impl_.c_),
        PROTOBUF_FIELD_OFFSET(::baseprotocol::FileHeaderData, _impl_.numbitsinzz_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::baseprotocol::Ciphertext)},
        {12, -1, -1, sizeof(::baseprotocol::RecievedCipherText)},
        {21, -1, -1, sizeof(::baseprotocol::FileUpload)},
        {33, -1, -1, sizeof(::baseprotocol::FileChunk)},
        {42, -1, -1, sizeof(::baseprotocol::FileHeaderData)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::baseprotocol::_Ciphertext_default_instance_._instance,
    &::baseprotocol::_RecievedCipherText_default_instance_._instance,
    &::baseprotocol::_FileUpload_default_instance_._instance,
    &::baseprotocol::_FileChunk_default_instance_._instance,
    &::baseprotocol::_FileHeaderData_default_instance_._instance,
};
const char descriptor_table_protodef_baseprotocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022baseprotocol.proto\022\014baseprotocol\"I\n\nCi"
    "phertext\022\016\n\006cprime\030\001 \001(\014\022\n\n\002iv\030\002 \001(\t\022\t\n\001"
    "c\030\003 \001(\t\022\024\n\014cprimeLength\030\004 \001(\003\"!\n\022Recieve"
    "dCipherText\022\013\n\003msg\030\001 \001(\t\"z\n\nFileUpload\022+"
    "\n\003fhd\030\001 \001(\0132\034.baseprotocol.FileHeaderDat"
    "aH\000\022%\n\002fc\030\002 \001(\0132\027.baseprotocol.FileChunk"
    "H\000\022\020\n\006foobar\030\003 \001(\tH\000B\006\n\004file\"\"\n\tFileChun"
    "k\022\025\n\rfileDataChunk\030\001 \001(\014\"b\n\016FileHeaderDa"
    "ta\022\022\n\nclientName\030\001 \001(\t\022\020\n\010filename\030\002 \001(\t"
    "\022\n\n\002iv\030\003 \001(\014\022\t\n\001c\030\004 \001(\014\022\023\n\013numbitsinZZ\030\005"
    " \001(\0032g\n\021BasicStringServer\022R\n\022HandleUploa"
    "dString\022\030.baseprotocol.Ciphertext\032 .base"
    "protocol.RecievedCipherText\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_baseprotocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_baseprotocol_2eproto = {
    false,
    false,
    517,
    descriptor_table_protodef_baseprotocol_2eproto,
    "baseprotocol.proto",
    &descriptor_table_baseprotocol_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_baseprotocol_2eproto::offsets,
    file_level_enum_descriptors_baseprotocol_2eproto,
    file_level_service_descriptors_baseprotocol_2eproto,
};
namespace baseprotocol {
// ===================================================================

class Ciphertext::_Internal {
 public:
};

Ciphertext::Ciphertext(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:baseprotocol.Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::baseprotocol::Ciphertext& from_msg)
      : cprime_(arena, from.cprime_),
        iv_(arena, from.iv_),
        c_(arena, from.c_),
        _cached_size_{0} {}

Ciphertext::Ciphertext(
    ::google::protobuf::Arena* arena,
    const Ciphertext& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Ciphertext* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.cprimelength_ = from._impl_.cprimelength_;

  // @@protoc_insertion_point(copy_constructor:baseprotocol.Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : cprime_(arena),
        iv_(arena),
        c_(arena),
        _cached_size_{0} {}

inline void Ciphertext::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.cprimelength_ = {};
}
Ciphertext::~Ciphertext() {
  // @@protoc_insertion_point(destructor:baseprotocol.Ciphertext)
  SharedDtor(*this);
}
inline void Ciphertext::SharedDtor(MessageLite& self) {
  Ciphertext& this_ = static_cast<Ciphertext&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.cprime_.Destroy();
  this_._impl_.iv_.Destroy();
  this_._impl_.c_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Ciphertext::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Ciphertext(arena);
}
constexpr auto Ciphertext::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Ciphertext),
                                            alignof(Ciphertext));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Ciphertext::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Ciphertext_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Ciphertext::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Ciphertext>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Ciphertext::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Ciphertext>(), &Ciphertext::ByteSizeLong,
            &Ciphertext::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_._cached_size_),
        false,
    },
    &Ciphertext::kDescriptorMethods,
    &descriptor_table_baseprotocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Ciphertext::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 35, 2> Ciphertext::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::baseprotocol::Ciphertext>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 cprimeLength = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Ciphertext, _impl_.cprimelength_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.cprimelength_)}},
    // bytes cprime = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.cprime_)}},
    // string iv = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.iv_)}},
    // string c = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.c_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes cprime = 1;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.cprime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string iv = 2;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.iv_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string c = 3;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.c_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 cprimeLength = 4;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.cprimelength_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\27\0\2\1\0\0\0\0"
    "baseprotocol.Ciphertext"
    "iv"
    "c"
  }},
};

PROTOBUF_NOINLINE void Ciphertext::Clear() {
// @@protoc_insertion_point(message_clear_start:baseprotocol.Ciphertext)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cprime_.ClearToEmpty();
  _impl_.iv_.ClearToEmpty();
  _impl_.c_.ClearToEmpty();
  _impl_.cprimelength_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Ciphertext::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Ciphertext& this_ = static_cast<const Ciphertext&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Ciphertext::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Ciphertext& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:baseprotocol.Ciphertext)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes cprime = 1;
          if (!this_._internal_cprime().empty()) {
            const std::string& _s = this_._internal_cprime();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // string iv = 2;
          if (!this_._internal_iv().empty()) {
            const std::string& _s = this_._internal_iv();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "baseprotocol.Ciphertext.iv");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string c = 3;
          if (!this_._internal_c().empty()) {
            const std::string& _s = this_._internal_c();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "baseprotocol.Ciphertext.c");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // int64 cprimeLength = 4;
          if (this_._internal_cprimelength() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<4>(
                    stream, this_._internal_cprimelength(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:baseprotocol.Ciphertext)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Ciphertext::ByteSizeLong(const MessageLite& base) {
          const Ciphertext& this_ = static_cast<const Ciphertext&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Ciphertext::ByteSizeLong() const {
          const Ciphertext& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:baseprotocol.Ciphertext)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes cprime = 1;
            if (!this_._internal_cprime().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_cprime());
            }
            // string iv = 2;
            if (!this_._internal_iv().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_iv());
            }
            // string c = 3;
            if (!this_._internal_c().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_c());
            }
            // int64 cprimeLength = 4;
            if (this_._internal_cprimelength() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_cprimelength());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Ciphertext::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Ciphertext*>(&to_msg);
  auto& from = static_cast<const Ciphertext&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:baseprotocol.Ciphertext)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_cprime().empty()) {
    _this->_internal_set_cprime(from._internal_cprime());
  }
  if (!from._internal_iv().empty()) {
    _this->_internal_set_iv(from._internal_iv());
  }
  if (!from._internal_c().empty()) {
    _this->_internal_set_c(from._internal_c());
  }
  if (from._internal_cprimelength() != 0) {
    _this->_impl_.cprimelength_ = from._impl_.cprimelength_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Ciphertext::CopyFrom(const Ciphertext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baseprotocol.Ciphertext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Ciphertext::InternalSwap(Ciphertext* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cprime_, &other->_impl_.cprime_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.iv_, &other->_impl_.iv_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.c_, &other->_impl_.c_, arena);
        swap(_impl_.cprimelength_, other->_impl_.cprimelength_);
}

::google::protobuf::Metadata Ciphertext::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RecievedCipherText::_Internal {
 public:
};

RecievedCipherText::RecievedCipherText(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:baseprotocol.RecievedCipherText)
}
inline PROTOBUF_NDEBUG_INLINE RecievedCipherText::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::baseprotocol::RecievedCipherText& from_msg)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

RecievedCipherText::RecievedCipherText(
    ::google::protobuf::Arena* arena,
    const RecievedCipherText& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RecievedCipherText* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:baseprotocol.RecievedCipherText)
}
inline PROTOBUF_NDEBUG_INLINE RecievedCipherText::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void RecievedCipherText::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RecievedCipherText::~RecievedCipherText() {
  // @@protoc_insertion_point(destructor:baseprotocol.RecievedCipherText)
  SharedDtor(*this);
}
inline void RecievedCipherText::SharedDtor(MessageLite& self) {
  RecievedCipherText& this_ = static_cast<RecievedCipherText&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RecievedCipherText::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RecievedCipherText(arena);
}
constexpr auto RecievedCipherText::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RecievedCipherText),
                                            alignof(RecievedCipherText));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RecievedCipherText::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RecievedCipherText_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RecievedCipherText::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RecievedCipherText>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RecievedCipherText::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RecievedCipherText>(), &RecievedCipherText::ByteSizeLong,
            &RecievedCipherText::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RecievedCipherText, _impl_._cached_size_),
        false,
    },
    &RecievedCipherText::kDescriptorMethods,
    &descriptor_table_baseprotocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RecievedCipherText::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> RecievedCipherText::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::baseprotocol::RecievedCipherText>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msg = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecievedCipherText, _impl_.msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string msg = 1;
    {PROTOBUF_FIELD_OFFSET(RecievedCipherText, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\37\3\0\0\0\0\0\0"
    "baseprotocol.RecievedCipherText"
    "msg"
  }},
};

PROTOBUF_NOINLINE void RecievedCipherText::Clear() {
// @@protoc_insertion_point(message_clear_start:baseprotocol.RecievedCipherText)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RecievedCipherText::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RecievedCipherText& this_ = static_cast<const RecievedCipherText&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RecievedCipherText::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RecievedCipherText& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:baseprotocol.RecievedCipherText)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string msg = 1;
          if (!this_._internal_msg().empty()) {
            const std::string& _s = this_._internal_msg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "baseprotocol.RecievedCipherText.msg");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:baseprotocol.RecievedCipherText)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RecievedCipherText::ByteSizeLong(const MessageLite& base) {
          const RecievedCipherText& this_ = static_cast<const RecievedCipherText&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RecievedCipherText::ByteSizeLong() const {
          const RecievedCipherText& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:baseprotocol.RecievedCipherText)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string msg = 1;
            if (!this_._internal_msg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msg());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RecievedCipherText::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecievedCipherText*>(&to_msg);
  auto& from = static_cast<const RecievedCipherText&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:baseprotocol.RecievedCipherText)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecievedCipherText::CopyFrom(const RecievedCipherText& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baseprotocol.RecievedCipherText)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RecievedCipherText::InternalSwap(RecievedCipherText* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
}

::google::protobuf::Metadata RecievedCipherText::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileUpload::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::baseprotocol::FileUpload, _impl_._oneof_case_);
};

void FileUpload::set_allocated_fhd(::baseprotocol::FileHeaderData* fhd) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_file();
  if (fhd) {
    ::google::protobuf::Arena* submessage_arena = fhd->GetArena();
    if (message_arena != submessage_arena) {
      fhd = ::google::protobuf::internal::GetOwnedMessage(message_arena, fhd, submessage_arena);
    }
    set_has_fhd();
    _impl_.file_.fhd_ = fhd;
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileUpload.fhd)
}
void FileUpload::set_allocated_fc(::baseprotocol::FileChunk* fc) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_file();
  if (fc) {
    ::google::protobuf::Arena* submessage_arena = fc->GetArena();
    if (message_arena != submessage_arena) {
      fc = ::google::protobuf::internal::GetOwnedMessage(message_arena, fc, submessage_arena);
    }
    set_has_fc();
    _impl_.file_.fc_ = fc;
  }
  // @@protoc_insertion_point(field_set_allocated:baseprotocol.FileUpload.fc)
}
FileUpload::FileUpload(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:baseprotocol.FileUpload)
}
inline PROTOBUF_NDEBUG_INLINE FileUpload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::baseprotocol::FileUpload& from_msg)
      : file_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

FileUpload::FileUpload(
    ::google::protobuf::Arena* arena,
    const FileUpload& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileUpload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (file_case()) {
    case FILE_NOT_SET:
      break;
      case kFhd:
        _impl_.file_.fhd_ = ::google::protobuf::Message::CopyConstruct<::baseprotocol::FileHeaderData>(arena, *from._impl_.file_.fhd_);
        break;
      case kFc:
        _impl_.file_.fc_ = ::google::protobuf::Message::CopyConstruct<::baseprotocol::FileChunk>(arena, *from._impl_.file_.fc_);
        break;
      case kFoobar:
        new (&_impl_.file_.foobar_) decltype(_impl_.file_.foobar_){arena, from._impl_.file_.foobar_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:baseprotocol.FileUpload)
}
inline PROTOBUF_NDEBUG_INLINE FileUpload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : file_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void FileUpload::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileUpload::~FileUpload() {
  // @@protoc_insertion_point(destructor:baseprotocol.FileUpload)
  SharedDtor(*this);
}
inline void FileUpload::SharedDtor(MessageLite& self) {
  FileUpload& this_ = static_cast<FileUpload&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_file()) {
    this_.clear_file();
  }
  this_._impl_.~Impl_();
}

void FileUpload::clear_file() {
// @@protoc_insertion_point(one_of_clear_start:baseprotocol.FileUpload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (file_case()) {
    case kFhd: {
      if (GetArena() == nullptr) {
        delete _impl_.file_.fhd_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.file_.fhd_);
      }
      break;
    }
    case kFc: {
      if (GetArena() == nullptr) {
        delete _impl_.file_.fc_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.file_.fc_);
      }
      break;
    }
    case kFoobar: {
      _impl_.file_.foobar_.Destroy();
      break;
    }
    case FILE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = FILE_NOT_SET;
}


inline void* FileUpload::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileUpload(arena);
}
constexpr auto FileUpload::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FileUpload),
                                            alignof(FileUpload));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileUpload::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileUpload_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileUpload::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileUpload>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileUpload::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileUpload>(), &FileUpload::ByteSizeLong,
            &FileUpload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileUpload, _impl_._cached_size_),
        false,
    },
    &FileUpload::kDescriptorMethods,
    &descriptor_table_baseprotocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileUpload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 38, 2> FileUpload::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::baseprotocol::FileUpload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .baseprotocol.FileHeaderData fhd = 1;
    {PROTOBUF_FIELD_OFFSET(FileUpload, _impl_.file_.fhd_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .baseprotocol.FileChunk fc = 2;
    {PROTOBUF_FIELD_OFFSET(FileUpload, _impl_.file_.fc_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // string foobar = 3;
    {PROTOBUF_FIELD_OFFSET(FileUpload, _impl_.file_.foobar_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::baseprotocol::FileHeaderData>()},
    {::_pbi::TcParser::GetTable<::baseprotocol::FileChunk>()},
  }}, {{
    "\27\0\0\6\0\0\0\0"
    "baseprotocol.FileUpload"
    "foobar"
  }},
};

PROTOBUF_NOINLINE void FileUpload::Clear() {
// @@protoc_insertion_point(message_clear_start:baseprotocol.FileUpload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_file();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileUpload::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileUpload& this_ = static_cast<const FileUpload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileUpload::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileUpload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:baseprotocol.FileUpload)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.file_case()) {
            case kFhd: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1, *this_._impl_.file_.fhd_, this_._impl_.file_.fhd_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kFc: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.file_.fc_, this_._impl_.file_.fc_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kFoobar: {
              const std::string& _s = this_._internal_foobar();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "baseprotocol.FileUpload.foobar");
              target = stream->WriteStringMaybeAliased(3, _s, target);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:baseprotocol.FileUpload)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileUpload::ByteSizeLong(const MessageLite& base) {
          const FileUpload& this_ = static_cast<const FileUpload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileUpload::ByteSizeLong() const {
          const FileUpload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:baseprotocol.FileUpload)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.file_case()) {
            // .baseprotocol.FileHeaderData fhd = 1;
            case kFhd: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.file_.fhd_);
              break;
            }
            // .baseprotocol.FileChunk fc = 2;
            case kFc: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.file_.fc_);
              break;
            }
            // string foobar = 3;
            case kFoobar: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_foobar());
              break;
            }
            case FILE_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileUpload::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileUpload*>(&to_msg);
  auto& from = static_cast<const FileUpload&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:baseprotocol.FileUpload)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_file();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kFhd: {
        if (oneof_needs_init) {
          _this->_impl_.file_.fhd_ =
              ::google::protobuf::Message::CopyConstruct<::baseprotocol::FileHeaderData>(arena, *from._impl_.file_.fhd_);
        } else {
          _this->_impl_.file_.fhd_->MergeFrom(from._internal_fhd());
        }
        break;
      }
      case kFc: {
        if (oneof_needs_init) {
          _this->_impl_.file_.fc_ =
              ::google::protobuf::Message::CopyConstruct<::baseprotocol::FileChunk>(arena, *from._impl_.file_.fc_);
        } else {
          _this->_impl_.file_.fc_->MergeFrom(from._internal_fc());
        }
        break;
      }
      case kFoobar: {
        if (oneof_needs_init) {
          _this->_impl_.file_.foobar_.InitDefault();
        }
        _this->_impl_.file_.foobar_.Set(from._internal_foobar(), arena);
        break;
      }
      case FILE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileUpload::CopyFrom(const FileUpload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baseprotocol.FileUpload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileUpload::InternalSwap(FileUpload* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.file_, other->_impl_.file_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata FileUpload::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileChunk::_Internal {
 public:
};

FileChunk::FileChunk(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:baseprotocol.FileChunk)
}
inline PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::baseprotocol::FileChunk& from_msg)
      : filedatachunk_(arena, from.filedatachunk_),
        _cached_size_{0} {}

FileChunk::FileChunk(
    ::google::protobuf::Arena* arena,
    const FileChunk& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileChunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:baseprotocol.FileChunk)
}
inline PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filedatachunk_(arena),
        _cached_size_{0} {}

inline void FileChunk::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileChunk::~FileChunk() {
  // @@protoc_insertion_point(destructor:baseprotocol.FileChunk)
  SharedDtor(*this);
}
inline void FileChunk::SharedDtor(MessageLite& self) {
  FileChunk& this_ = static_cast<FileChunk&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filedatachunk_.Destroy();
  this_._impl_.~Impl_();
}

inline void* FileChunk::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileChunk(arena);
}
constexpr auto FileChunk::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileChunk),
                                            alignof(FileChunk));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileChunk::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileChunk_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileChunk::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileChunk>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileChunk::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileChunk>(), &FileChunk::ByteSizeLong,
            &FileChunk::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._cached_size_),
        false,
    },
    &FileChunk::kDescriptorMethods,
    &descriptor_table_baseprotocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileChunk::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FileChunk::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::baseprotocol::FileChunk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes fileDataChunk = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.filedatachunk_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes fileDataChunk = 1;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.filedatachunk_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void FileChunk::Clear() {
// @@protoc_insertion_point(message_clear_start:baseprotocol.FileChunk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filedatachunk_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileChunk::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileChunk& this_ = static_cast<const FileChunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileChunk::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileChunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:baseprotocol.FileChunk)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes fileDataChunk = 1;
          if (!this_._internal_filedatachunk().empty()) {
            const std::string& _s = this_._internal_filedatachunk();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:baseprotocol.FileChunk)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileChunk::ByteSizeLong(const MessageLite& base) {
          const FileChunk& this_ = static_cast<const FileChunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileChunk::ByteSizeLong() const {
          const FileChunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:baseprotocol.FileChunk)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bytes fileDataChunk = 1;
            if (!this_._internal_filedatachunk().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_filedatachunk());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileChunk::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileChunk*>(&to_msg);
  auto& from = static_cast<const FileChunk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:baseprotocol.FileChunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filedatachunk().empty()) {
    _this->_internal_set_filedatachunk(from._internal_filedatachunk());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileChunk::CopyFrom(const FileChunk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baseprotocol.FileChunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileChunk::InternalSwap(FileChunk* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filedatachunk_, &other->_impl_.filedatachunk_, arena);
}

::google::protobuf::Metadata FileChunk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileHeaderData::_Internal {
 public:
};

FileHeaderData::FileHeaderData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:baseprotocol.FileHeaderData)
}
inline PROTOBUF_NDEBUG_INLINE FileHeaderData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::baseprotocol::FileHeaderData& from_msg)
      : clientname_(arena, from.clientname_),
        filename_(arena, from.filename_),
        iv_(arena, from.iv_),
        c_(arena, from.c_),
        _cached_size_{0} {}

FileHeaderData::FileHeaderData(
    ::google::protobuf::Arena* arena,
    const FileHeaderData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileHeaderData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.numbitsinzz_ = from._impl_.numbitsinzz_;

  // @@protoc_insertion_point(copy_constructor:baseprotocol.FileHeaderData)
}
inline PROTOBUF_NDEBUG_INLINE FileHeaderData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : clientname_(arena),
        filename_(arena),
        iv_(arena),
        c_(arena),
        _cached_size_{0} {}

inline void FileHeaderData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.numbitsinzz_ = {};
}
FileHeaderData::~FileHeaderData() {
  // @@protoc_insertion_point(destructor:baseprotocol.FileHeaderData)
  SharedDtor(*this);
}
inline void FileHeaderData::SharedDtor(MessageLite& self) {
  FileHeaderData& this_ = static_cast<FileHeaderData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.clientname_.Destroy();
  this_._impl_.filename_.Destroy();
  this_._impl_.iv_.Destroy();
  this_._impl_.c_.Destroy();
  this_._impl_.~Impl_();
}

inline void* FileHeaderData::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileHeaderData(arena);
}
constexpr auto FileHeaderData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileHeaderData),
                                            alignof(FileHeaderData));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileHeaderData::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileHeaderData_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileHeaderData::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileHeaderData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileHeaderData::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileHeaderData>(), &FileHeaderData::ByteSizeLong,
            &FileHeaderData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_._cached_size_),
        false,
    },
    &FileHeaderData::kDescriptorMethods,
    &descriptor_table_baseprotocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileHeaderData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 54, 2> FileHeaderData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::baseprotocol::FileHeaderData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string clientName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.clientname_)}},
    // string filename = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.filename_)}},
    // bytes iv = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.iv_)}},
    // bytes c = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.c_)}},
    // int64 numbitsinZZ = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileHeaderData, _impl_.numbitsinzz_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.numbitsinzz_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string clientName = 1;
    {PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.clientname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string filename = 2;
    {PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes iv = 3;
    {PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.iv_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes c = 4;
    {PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.c_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int64 numbitsinZZ = 5;
    {PROTOBUF_FIELD_OFFSET(FileHeaderData, _impl_.numbitsinzz_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\33\12\10\0\0\0\0\0"
    "baseprotocol.FileHeaderData"
    "clientName"
    "filename"
  }},
};

PROTOBUF_NOINLINE void FileHeaderData::Clear() {
// @@protoc_insertion_point(message_clear_start:baseprotocol.FileHeaderData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clientname_.ClearToEmpty();
  _impl_.filename_.ClearToEmpty();
  _impl_.iv_.ClearToEmpty();
  _impl_.c_.ClearToEmpty();
  _impl_.numbitsinzz_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileHeaderData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileHeaderData& this_ = static_cast<const FileHeaderData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileHeaderData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileHeaderData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:baseprotocol.FileHeaderData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string clientName = 1;
          if (!this_._internal_clientname().empty()) {
            const std::string& _s = this_._internal_clientname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "baseprotocol.FileHeaderData.clientName");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string filename = 2;
          if (!this_._internal_filename().empty()) {
            const std::string& _s = this_._internal_filename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "baseprotocol.FileHeaderData.filename");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // bytes iv = 3;
          if (!this_._internal_iv().empty()) {
            const std::string& _s = this_._internal_iv();
            target = stream->WriteBytesMaybeAliased(3, _s, target);
          }

          // bytes c = 4;
          if (!this_._internal_c().empty()) {
            const std::string& _s = this_._internal_c();
            target = stream->WriteBytesMaybeAliased(4, _s, target);
          }

          // int64 numbitsinZZ = 5;
          if (this_._internal_numbitsinzz() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<5>(
                    stream, this_._internal_numbitsinzz(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:baseprotocol.FileHeaderData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileHeaderData::ByteSizeLong(const MessageLite& base) {
          const FileHeaderData& this_ = static_cast<const FileHeaderData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileHeaderData::ByteSizeLong() const {
          const FileHeaderData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:baseprotocol.FileHeaderData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string clientName = 1;
            if (!this_._internal_clientname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_clientname());
            }
            // string filename = 2;
            if (!this_._internal_filename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filename());
            }
            // bytes iv = 3;
            if (!this_._internal_iv().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_iv());
            }
            // bytes c = 4;
            if (!this_._internal_c().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_c());
            }
            // int64 numbitsinZZ = 5;
            if (this_._internal_numbitsinzz() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_numbitsinzz());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileHeaderData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileHeaderData*>(&to_msg);
  auto& from = static_cast<const FileHeaderData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:baseprotocol.FileHeaderData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_clientname().empty()) {
    _this->_internal_set_clientname(from._internal_clientname());
  }
  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_iv().empty()) {
    _this->_internal_set_iv(from._internal_iv());
  }
  if (!from._internal_c().empty()) {
    _this->_internal_set_c(from._internal_c());
  }
  if (from._internal_numbitsinzz() != 0) {
    _this->_impl_.numbitsinzz_ = from._impl_.numbitsinzz_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileHeaderData::CopyFrom(const FileHeaderData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baseprotocol.FileHeaderData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileHeaderData::InternalSwap(FileHeaderData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientname_, &other->_impl_.clientname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.iv_, &other->_impl_.iv_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.c_, &other->_impl_.c_, arena);
        swap(_impl_.numbitsinzz_, other->_impl_.numbitsinzz_);
}

::google::protobuf::Metadata FileHeaderData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace baseprotocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_baseprotocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
