#include "actors/Client.hpp"
#include <boost/lexical_cast.hpp>
#include <boost/lexical_cast/bad_lexical_cast.hpp>
#include <boost/program_options.hpp>
#include <boost/program_options/variables_map.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree.hpp>

/**
 * how to use this:
 *
 * you need to run one of the networked-aud1024/2048/4096 to genearte a config file
 * you need to have a file of hashes like the one generated by HashGenerator.py in 
 * the scripts subfolder
 *
 * call $./base-client-test -c config.json, -i hashes.txt -p test
 */

int main(int argc, char *argv[]) {
  namespace po = boost::program_options;
  po::options_description desc("Allowed options");

  desc.add_options()("help,h", "produce help message")(
      "inputfile,i", po::value<std::string>(), "File of inputs that the Client wants to send")(
      "config,c", po::value<std::string>()->default_value("config.json"),"JSON config file to read from")(
      "pinput,p", po::value<std::string>(), "plaintext value for the client");

  po::variables_map vm;
  po::store(po::parse_command_line(argc, argv, desc), vm);
  po::notify(vm);

  std::string configPath;
  std::string clientPlaintext;
  std::string infilePath;
  std::string embedding;

  if (vm.count("help")) {
    std::cout << desc << std::endl;
    return 0;
  }

  // Example of how to access parsed options
  if (vm.count("inputfile")) {
    infilePath = vm["inputfile"].as<std::string>();
  }

  if (vm.count("config")) {
    configPath = vm["config"].as<std::string>();
  }

  if (vm.count("pinput")) {
    clientPlaintext = vm["pinput"].as<std::string>();
  }


  std::filesystem::path config(configPath);
  std::filesystem::path infile(infilePath);

  actors::JSONBasicClientFactory cfac(config);
  std::unique_ptr<actors::BasicDpsiClient> clientTest = cfac.CreateClient();

  std::chrono::milliseconds time_ms;
  
  std::chrono::high_resolution_clock::time_point start;
  std::chrono::high_resolution_clock::time_point end;
  std::ifstream hashFile(infile);

  while(std::getline(hashFile, embedding)) {
    start = std::chrono::high_resolution_clock::now();
    std::atomic_thread_fence(std::memory_order_seq_cst);

    clientTest->computeAndEncrypt(embedding, clientPlaintext);

    end = std::chrono::high_resolution_clock::now();
    time_ms += std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
    std::atomic_thread_fence(std::memory_order_seq_cst);
  }

  std::cout << time_ms.count() << " ms" << std::endl; 
}

